import { useEffect } from 'react';
import { motion } from 'motion/react';
import { ArrowRight, BarChart3, Bot, Check, CheckCircle2, ClipboardCheck, Database, FileSearch, MessageCircleMore, ShieldCheck, Sparkles, UsersRound, Zap } from 'lucide-react';
import PageMeta from '../components/PageMeta';
import { WHATSAPP_LINK } from '../constants';

const pains = [
  ['Customer inquiries sit inside WhatsApp chats', 'Every inquiry enters a visible lead tracker'],
  ['Follow-up depends on someone remembering', 'Next actions and reminders are clearly assigned'],
  ['Reports require copying between files', 'Organized data feeds a useful dashboard'],
  ['Owners chase staff for basic updates', 'Key activity is visible in one owner view'],
  ['Bookings and customer records are scattered', 'The customer journey follows a defined workflow'],
];

const systems = [
  { icon: MessageCircleMore, title: 'WhatsApp Lead Capture + CRM', fit: 'Consultants, real estate, clinics, training firms, retailers', copy: 'Capture inquiries, organize contact details, track status, set the next action, and make follow-up easier to manage.', features: ['Inquiry capture', 'Lead status and ownership', 'Follow-up reminders', 'Owner pipeline view'] },
  { icon: Bot, title: 'AI Sales & Follow-Up Assistant', fit: 'Small sales teams and service businesses', copy: 'Use AI to support—not replace—your team with inquiry summaries, response drafts, lead categories, and follow-up suggestions.', features: ['Inquiry summarization', 'Approved response templates', 'Lead classification', 'Human review before sending'] },
  { icon: BarChart3, title: 'Operations & Reporting Dashboard', fit: 'SMEs, managers, branches, and growing teams', copy: 'Organize existing business records and turn them into a clear view of sales, activity, outstanding work, or stock attention points.', features: ['Defined business metrics', 'Connected source records', 'Scheduled reporting', 'Attention flags'] },
  { icon: ClipboardCheck, title: 'NGO Reporting & Impact Dashboard', fit: 'NGOs, CBOs, county chapters, and field programs', copy: 'Standardize field reports, beneficiary records, evidence links, and program visibility without making reporting harder for field teams.', features: ['Activity collection forms', 'Evidence organization', 'Chapter or county views', 'Monthly report support'] },
  { icon: FileSearch, title: 'Agribusiness Traceability Lite', fit: 'Honey, food, and emerging product brands', copy: 'Create structured batch records and QR-linked product pages that make origin and product information easier to communicate.', features: ['Supplier and source records', 'Batch history', 'QR-linked information', 'Customer-facing passport'] },
  { icon: UsersRound, title: 'Client Intake & Appointment Workflow', fit: 'Clinics, gyms, consultants, salons, and law firms', copy: 'Create a consistent path from inquiry or booking to confirmation, internal action, and follow-up.', features: ['Structured intake', 'Booking confirmation', 'Team alerts', 'Return-visit reminders'] },
];

const principles = [
  { icon: Database, title: 'Client-owned accounts', copy: 'Production data, billing, and access should remain under the client’s control wherever possible.' },
  { icon: ShieldCheck, title: 'Privacy-conscious design', copy: 'Collect only what the workflow needs, define access clearly, and protect credentials and sensitive records.' },
  { icon: CheckCircle2, title: 'Human-supervised AI', copy: 'AI can draft and summarize, while people retain approval for important decisions and external communication.' },
  { icon: Zap, title: 'Adoption before complexity', copy: 'Start with a dependable, understandable system and add advanced integrations only when justified.' },
];

const BusinessSystemsPage = () => {
  useEffect(() => window.scrollTo(0, 0), []);
  return <>
    <PageMeta path="/business-systems-automation" title="WhatsApp CRM, Business Systems & Workflow Automation | Silatech Kenya" description="Explore practical WhatsApp lead management, CRM workflows, dashboards, AI-assisted follow-up, NGO reporting, and business automation for growing teams." />
    <section className="relative overflow-hidden bg-ink pb-24 pt-36 sm:pb-32 sm:pt-44"><div className="hero-grid absolute inset-0" /><div className="hero-orb absolute -left-40 -top-40 h-[650px] w-[650px]" /><div className="shell relative text-center"><span className="eyebrow-light"><Sparkles className="h-4 w-4" /> Business systems & workflow automation</span><h1 className="display-title mx-auto mt-6 max-w-5xl">Connect the work between your <span className="text-gradient">WhatsApp, spreadsheets, customers, and reports.</span></h1><p className="body-lg mx-auto mt-7 max-w-3xl text-slate-copy">We help growing organizations replace scattered manual routines with practical systems for lead follow-up, customer records, reporting, appointments, and daily visibility.</p><div className="mt-10 flex flex-col justify-center gap-3 sm:flex-row"><a href={WHATSAPP_LINK} target="_blank" rel="noreferrer" className="btn-primary">Book a systems diagnostic <ArrowRight className="h-4 w-4" /></a><a href="#systems" className="btn-light">See example systems</a></div></div></section>

    <section className="bg-cloud py-24 text-ink sm:py-32"><div className="shell"><div className="mx-auto max-w-3xl text-center"><span className="eyebrow">The operational gap</span><h2 className="section-title mt-5 !text-ink">Your tools may already be digital. The work between them is often still manual.</h2><p className="body-lg mt-6 text-slate-600">Silatech focuses on those gaps: the inquiry that was never logged, the customer who was not called back, and the report that arrives too late.</p></div><div className="mt-14 overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-card"><div className="grid grid-cols-2 border-b border-slate-200 bg-[#edf2f9] px-5 py-4 text-[10px] font-bold uppercase tracking-[.15em] text-slate-500 sm:px-8"><span>Before</span><span>After</span></div>{pains.map(([before, after]) => <div key={before} className="grid grid-cols-2 gap-5 border-b border-slate-100 px-5 py-5 last:border-0 sm:px-8"><p className="text-sm leading-6 text-slate-500">{before}</p><p className="flex gap-2 text-sm font-semibold leading-6 text-slate-800"><Check className="mt-1 h-4 w-4 shrink-0 text-cobalt" />{after}</p></div>)}</div></div></section>

    <section id="systems" className="bg-white py-24 text-ink sm:py-32"><div className="shell"><div className="grid gap-7 lg:grid-cols-[.9fr_1.1fr] lg:items-end"><div><span className="eyebrow">Flagship solutions</span><h2 className="section-title mt-5 !text-ink">Systems built around recognizable business problems.</h2></div><p className="body-lg max-w-2xl text-slate-600 lg:justify-self-end">These are solution patterns, not rigid software products. The final workflow is scoped around the client’s tools, users, data, and budget.</p></div><div className="mt-14 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{systems.map(({icon: Icon, title, fit, copy, features}, index) => <motion.article initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.04}} key={title} className="card-light flex flex-col p-7"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#eaf0ff] text-cobalt"><Icon className="h-5 w-5" /></span><h3 className="mt-7 text-xl font-bold !text-ink">{title}</h3><p className="mt-2 text-[10px] font-bold uppercase tracking-[.12em] text-cobalt">Best for: {fit}</p><p className="mt-5 text-sm leading-6 text-slate-600">{copy}</p><ul className="mt-6 space-y-2 border-t border-slate-100 pt-5">{features.map(feature => <li key={feature} className="flex gap-2 text-xs font-semibold text-slate-700"><Check className="h-4 w-4 text-mint" />{feature}</li>)}</ul></motion.article>)}</div></div></section>

    <section className="relative overflow-hidden bg-ink py-24 sm:py-32"><div className="hero-grid absolute inset-0 opacity-35" /><div className="shell relative"><div className="mx-auto max-w-3xl text-center"><span className="eyebrow-light">A complete operating layer</span><h2 className="section-title mt-5">From first inquiry to the owner’s weekly view.</h2><p className="body-lg mt-6 text-slate-copy">A focused implementation can connect the most important steps while still using familiar, low-cost tools where appropriate.</p></div><div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{[['01','Capture','Form, website, or WhatsApp inquiry'],['02','Organize','Clean customer or activity record'],['03','Act','Reminder, team alert, or approved response'],['04','See','Dashboard and attention summary']].map(([number,title,copy]) => <article key={title} className="card-dark p-6"><span className="font-display text-xs font-bold text-mint">{number}</span><h3 className="mt-6 text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-copy">{copy}</p></article>)}</div><div className="mt-10 text-center"><p className="text-xs leading-5 text-slate-500">Advanced WhatsApp automation may require official WhatsApp Business Platform access, approved templates, consent, and third-party messaging charges. These requirements are confirmed during scoping.</p></div></div></section>

    <section className="bg-cloud py-24 text-ink sm:py-32"><div className="shell grid gap-12 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><div><span className="eyebrow">Responsible implementation</span><h2 className="section-title mt-5 !text-ink">Useful automation needs clear ownership and guardrails.</h2><p className="body-lg mt-6 text-slate-600">Security and privacy depend on the final tools, hosting, configuration, and client procedures. We address them during design instead of making blanket promises.</p></div><div className="grid gap-4 sm:grid-cols-2">{principles.map(({icon:Icon,title,copy}) => <article key={title} className="card-light p-6"><Icon className="h-5 w-5 text-cobalt" /><h3 className="mt-6 text-lg font-bold !text-ink">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{copy}</p></article>)}</div></div></section>

    <section className="bg-white py-24 text-ink sm:py-32"><div className="shell"><div className="rounded-[2rem] bg-[#eaf0ff] p-8 sm:p-12 lg:flex lg:items-center lg:justify-between"><div className="max-w-2xl"><span className="eyebrow">Start with diagnosis</span><h2 className="mt-5 font-display text-3xl font-bold leading-tight tracking-[-.03em] !text-ink sm:text-4xl">Find the workflow leak worth fixing first.</h2><p className="mt-5 text-base leading-7 text-slate-600">We review how the work happens today, identify the highest-value improvement, and recommend a realistic first system.</p></div><a href={WHATSAPP_LINK} target="_blank" rel="noreferrer" className="btn-dark mt-8 shrink-0 lg:mt-0">Book a systems diagnostic <ArrowRight className="h-4 w-4" /></a></div></div></section>
  </>;
};

export default BusinessSystemsPage;
